### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [cookiepal/cookiepal-gtm-template#5]
https://github.com/cookiepal/cookiepal-gtm-template/blob/198e66ab3463f0cd7fb4699a107765438238ea23/template.tpl#L491

When reviewing your template, we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by ysoares0209** [comment]
Hey
thank you for flagging.

See https://github.com/cookiepal/cookiepal-gtm-template/issues/6#issuecomment-2414231792
