### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [cookiepal/cookiepal-gtm-template#6]
https://github.com/cookiepal/cookiepal-gtm-template/blob/a3e9966bc8540157c1a39b516097515450367e4a/template.tpl#L78

When reviewing your template, we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by ysoares0209** [comment]
Hello
Thank you for flagging.

The issue has been addressed in #7
